# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY programming-languages.py /app

# Define the command to run the Python script when the container starts
ENTRYPOINT ["python", "programming-languages.py", "https://en.wikipedia.org/wiki/Comparison_of_programming_languages"]

